const _group = '宠装'
export default {
  笼玉环: { _group },
  笼玉镯: { _group },
  笼玉甲: { _group },
  嵌宝金环: { _group },
  嵌宝金腕: { _group },
  嵌宝金甲: { _group },
  玳瑁环: { _group },
  玳瑁护腕: { _group },
  玳瑁衣: { _group },
  七星宝环: { _group },
  七星宝腕: { _group },
  七星宝甲: { _group },
  缚龙圈: { _group },
  缚龙筋: { _group },
  缚龙甲: { _group },
  鸾尾环: { _group },
  凤翎护腕: { _group },
  凤凰彩衣: { _group },
  织锦颈圈: { _group },
  织锦彩带: { _group },
  织锦软褡: { _group },
}
